name: catalogo_filmes_flutter
description: Um catálogo de filmes usando Flutter, API e Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # API
  http: ^0.13.6

  # Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.12.0

  # YouTube player
  youtube_player_flutter: ^8.1.1

  # Ícones do iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
